"""External-benchmark validation points for the emulator UI.

Numbers come from `docs/BENCHMARK_SOURCES.md §2` (cross-check table). Each
entry is a real published or self-measured benchmark and the emulator's
prediction for the same scenario; `delta` is `(pred - real) / real`.

Edit this file when new validation points are added — the UI auto-loads it.
"""

VALIDATION_POINTS = [
    {
        "id": "2.1",
        "hw": "1xA100",
        "engine": "tensorrt",
        "scenario": "Mixtral 8x7B INT8, P_in=512, P_out=128, b=1",
        "metric": "decode/token",
        "real": 11.4,
        "pred": 11.1,
        "unit": "ms/token",
        "delta_pct": -2.6,
        "verdict": "✓",
        "source": "Baseten — Mixtral 8x7B / TRT-LLM / A100",
        "url": "https://www.baseten.co/blog/faster-mixtral-inference-with-tensorrt-llm-and-quantization/",
        "comment": "Калиброванная (после фикса MoE-memory bug, commit 4fdaa87).",
    },
    {
        "id": "2.2a",
        "hw": "1xA100",
        "engine": "vllm",
        "scenario": "Qwen2.5-7B AWQ, P_in=1, P_out=2048, b=1",
        "metric": "output throughput",
        "real": 148.0,
        "pred": 138.0,
        "unit": "tok/s",
        "delta_pct": -6.7,
        "verdict": "✓",
        "source": "Qwen Speed Benchmark — A100 / vLLM",
        "url": "https://qwen.readthedocs.io/en/latest/benchmark/speed_benchmark.html",
        "comment": "Single-stream, после калибровки α=0.45, β=0.44.",
    },
    {
        "id": "2.2b",
        "hw": "1xA100",
        "engine": "vllm",
        "scenario": "Qwen2.5-7B AWQ, P_in=6144, P_out=2048, b=1",
        "metric": "output throughput",
        "real": 137.6,
        "pred": 125.6,
        "unit": "tok/s",
        "delta_pct": -9.0,
        "verdict": "✓",
        "source": "Qwen Speed Benchmark — A100 / vLLM",
        "url": "https://qwen.readthedocs.io/en/latest/benchmark/speed_benchmark.html",
        "comment": "Long-context: KV-term доминирует, систематический недооцен ~9%.",
    },
    {
        "id": "2.3",
        "hw": "2xRTX-5090",
        "engine": "vllm",
        "scenario": "Qwen2.5-7B AWQ, P_in=1024, P_out=128, b=200",
        "metric": "total throughput",
        "real": 13953.87,
        "pred": 13826.8,
        "unit": "tok/s",
        "delta_pct": -0.9,
        "verdict": "✓✓",
        "source": "self — vllm bench (см. §1.3)",
        "url": "https://github.com/dedanimalfarm/llm-inference-emulator/blob/main/docs/BENCHMARK_SOURCES.md",
        "comment": "Self-consistency внутри откалиброванной области. Ожидаемо тесно.",
    },
    {
        "id": "2.4a",
        "hw": "1xH100",
        "engine": "vllm",
        "scenario": "Llama-3.1-8B BF16, P_in=256, P_out=256, b=1",
        "metric": "TTFT",
        "real": 72.0,
        "pred": 49.6,
        "unit": "ms",
        "delta_pct": -31.0,
        "verdict": "✗",
        "source": "Morphllm — H100 / vLLM",
        "url": "https://morphllm.com/blog/h100-vllm-llama3",
        "comment": "Roofline-undershoot — формула не учитывает фиксированный per-request overhead.",
    },
    {
        "id": "2.4b",
        "hw": "1xH100",
        "engine": "vllm",
        "scenario": "Llama-3.1-8B BF16, server stress, high concurrency",
        "metric": "throughput",
        "real": 12500.0,
        "pred": 5503.0,
        "unit": "tok/s",
        "delta_pct": -56.0,
        "verdict": "✗",
        "source": "Morphllm — H100 / vLLM",
        "url": "https://morphllm.com/blog/h100-vllm-llama3",
        "comment": "Calibration gap: batch_saturation=(45,7) с RTX-5090 не подходит H100; нужно ≈(92,5).",
    },
    # ----- A100-80GB calibration cross-checks (2026-05-16, Gemini session) -----
    {
        "id": "2.5",
        "hw": "1xA100-80",
        "engine": "vllm",
        "scenario": "Qwen-2.5-72B AWQ.4bit, b=32",
        "metric": "throughput",
        "real": 138.0,
        "pred": 134.5,
        "unit": "tok/s",
        "delta_pct": -2.5,
        "verdict": "✓",
        "source": "self — A100-80 vLLM calibration (Vast.ai)",
        "url": "https://github.com/dedanimalfarm/llm-inference-emulator/blob/main/results/A100_80_CALIBRATION_REPORT.md",
        "comment": "Self-consistency после α=0.537, β=0.560 калибровки. Внутри ±5%.",
    },
    {
        "id": "2.6",
        "hw": "1xA100-80",
        "engine": "llama.cpp",
        "scenario": "Llama 4 Scout IQ2_M (109B/17B MoE), b=1",
        "metric": "decode throughput",
        "real": 68.1,
        "pred": 66.4,
        "unit": "tok/s",
        "delta_pct": -2.5,
        "verdict": "✓",
        "source": "self — A100-80 llama-bench (Vast.ai)",
        "url": "https://github.com/dedanimalfarm/llm-inference-emulator/blob/main/results/A100_80_CALIBRATION_REPORT.md",
        "comment": "First-contact valid для 2026-моделей: MoE active-scaling + sliding_window=8192 работают как ожидалось.",
    },
    {
        "id": "2.7",
        "hw": "1xA100-80",
        "engine": "llama.cpp",
        "scenario": "Gemma 4 31B IQ2_M, b=1",
        "metric": "decode throughput",
        "real": 44.7,
        "pred": 46.2,
        "unit": "tok/s",
        "delta_pct": +3.3,
        "verdict": "✓",
        "source": "self — A100-80 llama-bench (Vast.ai)",
        "url": "https://github.com/dedanimalfarm/llm-inference-emulator/blob/main/results/A100_80_CALIBRATION_REPORT.md",
        "comment": "head_dim=256 + hybrid attention (sw=1024) попадают в роофлайн.",
    },
]
